auth0:
    audience: 1E4bHwGjDsGhgkLHcrlk0xemreuSXpnd

spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: create
