name: Gradle Build and publish image to github packages

on:
    push:
        branches:
            - master

jobs:
    build:
        uses: Nachoferra1894/ingsis-actions/.github/workflows/gradle-test.yml@main
    publish:
        needs: build
        uses: Nachoferra1894/ingsis-actions/.github/workflows/docker-image.yml@main
        with:
            image-name: snippet-Ui-managmet
            image-version: 0.0.1
